# Generated by Django 5.0 on 2024-01-08 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='biography',
            field=models.CharField(default='1900', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='types',
            field=models.CharField(choices=[('Records', 'Disques'), ('Clothing', 'Vetements'), ('Posters', 'Affiches'), ('Miscellaneous', 'Divers')], default='Miscellaneous', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='year',
            field=models.IntegerField(default='1800', validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
