version: "0.2"

networks:
  nw:
    name: my_network42
    driver: bridge

volumes:
  ircserv:
    driver: local
    name: irc_volume
    driver_opts:
      type: none
      o: bind
      device: /home/sdestann/data/irc
  weechat:
    driver: local
    name: wc_volume
    driver_opts:
      type: none
      o: bind
      device: /home/sdestann/data/wc

services:
 
  server_irc:
    container_name: irc_volume
    image: ircserv
    build: ./requirements/ircserv
    networks:
      - nw
    restart: unless-stopped
    volumes:
      - ircserv:/var/lib/ircserv
      
  weechat:
    container_name: wc_volume
    image: wc
    build: ./requirements/wc
    networks:
      - nw
    depends_on:
      - server_irc
    restart: unless-stopped
    volumes:
      - weechat:/var/lib/wc

      
