CREATE DATABASE IF NOT EXISTS wordpress;
SELECT * FROM wp_users WHERE user_login = '${MARIA_DB_LOGIN}';
DELETE FROM wp_users WHERE user_login = '${MARIA_DB_LOGIN}';
CREATE USER IF NOT EXISTS '${MARIA_DB_LOGIN}'@'%' IDENTIFIED BY '${MARIA_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON wordpress.* TO '${MARIA_DB_LOGIN}'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'test';

