# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sdestann <sdestann@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/08/14 10:38:18 by sdestann          #+#    #+#              #
#    Updated: 2023/08/14 10:53:41 by sdestann         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

### MISC ###

NAME = megaphone

SRCS = megaphone.cpp

CPPFLAGS = -Wall -Wextra -Werror -std=c++98

CC = c++

### RULES ###

all:
	$(CC) $(CPPFLAGS) $(SRCS) -o $(NAME)

clean:
	rm -rf megaphone
