services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    networks:
      - inception42
    ports:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    hostname: mariadb
    #init: true
    restart: always
    #stop_signal: SIGTERM
#---------------------------------------
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    networks:
      - inception42
    ports:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    hostname: wordpress
    #init: true
    restart: always
    #stop_signal: SIGTERM
    depends_on:
      - mariadb
#---------------------------------------
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - inception42
    ports:
      - "443:443"
      - "8080"
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    hostname: nginx
    #init: true
    restart: always
    #stop_signal: SIGTERM
    depends_on:
      - wordpress
########################################
volumes:
  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/sdestann/data/mariadb
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/sdestann/data/wordpress
########################################
networks:
  inception42:
    name: inception42
    driver: bridge